### ISSUE TITLE
Issues with React 16

### ISSUE THREAD

**Issue by hadfieldn** [chrisdibble/feform#5]
Hey Chris. I'm having some issues that I think may be caused by the library using some deprecated React features. I'll see if I can come up with a simple test project that duplicates the issue, but what I'm seeing is that after I include a Form component on a page, any component that comes after the Form in the DOM doesn't respond to click events.

I'm not positive where the problem is coming from, but I"m wondering if it can be due to these issues:

1. The project depends on React.PropTypes, which is deprecated in React 15 and will go away in React 16. This needs to be replaced by the new `prop-types` module.

2. Also, it looks like there is a dependency on the old `refs` attribute, which has been replaced by a `ref` callback.

I'm not sure if the second issue is related to the problem I'm seeing or not.

Any chance you'd be able to look into this in the near future?

**Comment by chrisdibble** [comment]
Hey @hadfieldn. I'll see what I can do over the weekend as we'll need this at my company anyhow. We haven't jumped into the beta yet for React 16. My guess is it's probably mainly due to the `prop-types` being extracted, but switching over to functional `refs` is simple enough as well.

**Comment by hadfieldn** [comment]
Thanks @chrisdibble!

**Comment by hadfieldn** [comment]
Fixed with #7
